### ISSUE TITLE
问题2 同步表数据之后，表的 comment 没能导入进来

### ISSUE THREAD

**Issue by zhmz1326** [jm-team/DevMasterWeb#1]
![default](https://cloud.githubusercontent.com/assets/285687/24538788/cc486e10-161d-11e7-876e-3c86f2a04718.png)

![qq 20170331142839](https://cloud.githubusercontent.com/assets/285687/24538984/e2ea91f6-161e-11e7-86ab-b71f406db123.png)

**Comment by crazylong** [comment]
配置链接参数
  Properties props =new Properties();
        props.setProperty("user", username);
        props.setProperty("password", password);
        props.setProperty("remarks", "true"); //设置可以获取remarks信息
        props.setProperty("useInformationSchema", "true");//设置可以获取tables remarks信息
