### ISSUE TITLE
模板克隆，没有克隆 参数配置

### ISSUE THREAD

**Issue by zhmz1326** [jm-team/DevMasterWeb#14]
要克隆的模板的参数

![qq 20170331144735](https://cloud.githubusercontent.com/assets/285687/24539416/01208692-1621-11e7-8b49-25f98f717349.png)

克隆之后的模板的参数

![qq 20170331144746](https://cloud.githubusercontent.com/assets/285687/24539423/05e1dfaa-1621-11e7-9da1-bf4542d52347.png)

**Comment by Yangjianbin** [comment]
Being solved

**Comment by zhmz1326** [comment]
已修复～
