### ISSUE TITLE
问题15 字段类型不统一

### ISSUE THREAD

**Issue by zhmz1326** [jm-team/DevMasterWeb#2]
MySQL导入进来的 字段类型 都是 大写

但是选择框的 都是小写，不统一 

![default](https://cloud.githubusercontent.com/assets/285687/24539059/3bc80308-161f-11e7-8366-2b47bd46c926.png)

**Comment by Yangjianbin** [comment]
lucky done

**Comment by zhmz1326** [comment]
将字段类型的select的option的值也修改为大写
