### ISSUE TITLE
共享模板添加失败

### ISSUE THREAD

**Issue by zhmz1326** [jm-team/DevMasterWeb#9]
共享模板 增加模板 输入信息，保存之后 界面没有重新刷新。手动刷新之后，发现 模板没有被添加成功。模板被添加到模板列表里去了

![qq 20170331144424](https://cloud.githubusercontent.com/assets/285687/24539322/90bdf4c0-1620-11e7-9a9f-f3b3a333b6c3.png)

![qq 20170331144402](https://cloud.githubusercontent.com/assets/285687/24539304/81e10f8c-1620-11e7-922d-89f44c25952a.png)

**Comment by Yangjianbin** [comment]
lucky done
